### PR TITLE
TCP Options

### PR DESCRIPTION
**Pull request by uRyanxD**
Note: TCPFastOpen does not improve performance much, in some tests done by a friend with bot attacks according to him it even got worse, if you agree I think it's a good thing not to add

### CODE REVIEW

**Comment by mechoriet** [comment]
From what I just read it could improve in servers that are backed by a proxy on the initial login or server switches since it doesn't need to reestablish a new connection fully since a sorta cookie gets set on both ends that they are "friends"/good folk
https://en.wikipedia.org/wiki/TCP_Fast_Open 

so it could start sending chunk data for example sooner then without it
since the buildup of a tcp connection is drastically shortened

but for standalone servers it not very useful since both sides need to have this enabled to work, and every player is in a different location and a highly likely chance there client doesn't have this enabled at all 

so this is more a behind a proxy kind of optimization for faster initial contact

**Comment by xIsm4** [comment]
> Note: TCPFastOpen does not improve performance much, in some tests done by a friend with bot attacks according to him it even got worse, if you agree I think it's a good thing not to add

I don't think it's right to use TFO in the backend, it would be a good pull-request in BungeeCord (because Velocity already has it) and compress chunks faster (making the connection faster) which is the point of this. As for the bot attack, I don't understand why PandaSpigot should mitigate it, it's not made for that.

**Comment by mechoriet** [comment]
I meant it in the proxy software(bungee/velocity) <-> lobbies/game modes kind of situations.
then if proxy software has this also enabled then subsequent connections to a lobby and gamemode should see improvement
the other side clients <-> pandaspigot won't see any benefit from this since its mainly for sequent connections that provide the token that is already known.
So it doesn't need to do the full handshake to establish the connection.

If I'm understanding the little reading I did about it?

**Comment by xIsm4** [comment]
> 

That's why i think is worth pull-request on BungeeCord. Velocity already had it

**Comment by uRyanxD** [comment]
I'm closing this PR because I don't have time to work on it

**Pull request closed without merging**
