### PR TITLE
Add support for io_uring

### PR DESCRIPTION
**Pull request by skbeh**
This only works when not using unix domain socket
and compression is disabled because
the netty io_uring transport does not support
unix domain socket and the client can not decode
compressed packets sent with io_uring.

### CODE REVIEW

**Comment by MachineBreaker** [comment]
Disable this by default

**Comment by skbeh** [comment]
@MachineBreaker Done.

**Comment by uRyanxD** [comment]
Hello, thanks for the pullrequest, however, we decided not to add support for IO_URING for now as it is an experimental feature and for security reasons as Kenny said [here](https://github.com/PaperMC/Paper/pull/9141#issuecomment-1913517266).

**Comment by andreasdc** [comment]
What's not secure with this solution? I heard that io_uring brings great performance.

**Pull request closed without merging**
