### PR TITLE
fix: EntitySoundEvent null pointer exception

### PR DESCRIPTION
**Pull request by rejuvenate7**
fixes issue #231

### CODE REVIEW

**Comment by MichaelKozlovOfficial** [comment]
deleted the patch, fixed the issues? Don't be ridiculous.

**Comment by MichaelKozlovOfficial** [comment]
why don't you fix patch instead of delete?

**Comment by iamnoksio** [comment]
> why don't you fix patch instead of delete?

why backporting instead of actually fixing it? skill issue?

**Comment by iamnoksio** [comment]
https://stackoverflow.com/questions/218384/what-is-a-nullpointerexception-and-how-do-i-fix-it if you ever wonder what a NPE is

**Comment by iamnoksio** [comment]
it's only because EnderDragon sounds is returning a null entity; just set the EnderDragon as entity --'

**Comment by uRyanxD** [comment]
> it's only because EnderDragon sounds is returning a null entity; just set the EnderDragon as entity --'
> 
> NAH F THE EDIT BRO

I think the problem is that the event is using entity.bukkitEntity instead of the entity.getBukkitEntity() method

**Comment by uRyanxD** [comment]
@rejuvenate7,
Thanks for the pull request, however this is not the solution. The solution is to use getBukkitEntity() instead of entity.bukkitEntity, I will send a pullrequest with the fix later

**Pull request closed without merging**
