### PR TITLE
Only call the event if there is a listener that uses it

### PR DESCRIPTION
**Pull request by uRyanxD**

### CODE REVIEW

**Comment by iamnoksio** [comment]
this is useless, even if the event is fire it still do nothing

**Comment by iamnoksio** [comment]
this is useless, even if the event is fire it still do nothing

**Comment by uRyanxD** [comment]
> this is useless, even if the event is fire it still do nothing

Yes, even if it is called, it doesn't do anything, but it doesn't make sense to call it if it doesn't do anything

**Comment by iamnoksio** [comment]
> > this is useless, even if the event is fire it still do nothing
> 
> Yes, even if it is called, it doesn't do anything, but it doesn't make sense to call it if it doesn't do anything

even if it doesnt make sens to you, it still dont change any performances/fix something, and if it was absolutely right you'd do it for every single event

**Pull request closed without merging**
