### PR TITLE
Patch scripts rewrite

### PR DESCRIPTION
**Pull request by hpfxd**
Based on the scripts present in [Paper 1.16.5](https://github.com/PaperMC/Paper/tree/ver/1.16.5/scripts).

Main highlights:
- Cleaned up a lot of the hackyness of the old scripts, such as patching upstream scripts.
- Applying patches should be much faster on some configurations and use less resources.
- Building no longer requires Maven to be installed (ported `paperclip-maven-plugin` to Gradle).

### CODE REVIEW

**Comment by mechoriet** [comment]
the only odd thing I so far found was that applying after it was already applied
it reapplies all the all other patches all the way back to Craftbukkit again too

```bash
~/panda-patch-rewrite (patch-system-rewrite) $ ./panda patch
Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Creating remapped jar...
Extracting NMS classes...
Applying CraftBukkit patches to NMS...
Patching Village.java < nms-patches/Village.patch
Patching EntityThrownExpBottle.java < nms-patches/EntityThrownExpBottle.patch
Patching BlockDaylightDetector.java < nms-patches/BlockDaylightDetector.patch
...
HEAD is now at 741a1bdf3 Upgrade log4j version
Rebuilding Forked projects....
Resetting Spigot-API to Bukkit...
HEAD is now at 01d18206 Add non-mutative getCrossProduct method to Vector.
  Applying patches to Spigot-API...
Applying: POM Changes
Applying: Spigot Timings
Applying: Add PlayerItemDamageEvent
Applying: BungeeCord Support
...
Applying: Add restart API.
  Patches applied cleanly to Spigot-API
Resetting Spigot-Server to CraftBukkit...
HEAD is now at 25c3d0140 CraftBukkit $ Fri Dec  2 23:26:42 CET 2022
  Applying patches to Spigot-Server...
Applying: POM Changes
Applying: mc-dev imports
Applying: Skeleton API Implementations
Applying: Obfuscation Helpers
Applying: Spigot Configuration
Applying: Better Chunk Tick Selection
...
Applying: Don't sleep between chunk saves
  Patches applied cleanly to Spigot-Server
Resetting PaperSpigot-API to Spigot-API...
HEAD is now at e6daa15d Add restart API.
  Applying patches to PaperSpigot-API...
Applying: POM changes
Applying: Add float methods to configs
Applying: Stop using spigot's website for timings
Applying: Player affects spawning API
Applying: Add getTPS method
...
Applying: Fix ServerListPingEvent flagging as Async
Applying: Fix ServerListPingEvent flagging as Async
Using index info to reconstruct a base tree...
M       src/main/java/org/bukkit/event/server/ServerEvent.java
M       src/main/java/org/bukkit/event/server/ServerListPingEvent.java
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
  Patches applied cleanly to PaperSpigot-API
Resetting PaperSpigot-Server to Spigot-Server...
HEAD is now at 55b81b81a Don't sleep between chunk saves
  Applying patches to PaperSpigot-Server...
Applying: POM Changes
Applying: PaperSpigot config files
Applying: mc-dev imports
...
Applying: PaperMC/Paper/GH-166
Applying: update log4j
  Patches applied cleanly to PaperSpigot-Server
Importing MC Dev
Resetting PandaSpigot-API to PaperSpigot-API...
HEAD is now at 1a95d3b4 Fix ServerListPingEvent flagging as Async
  Applying patches to PandaSpigot-API...
Applying: PandaSpigot version checking
Applying: Backport server tick events from Paper
Applying: Setup Gradle project
...
Applying: Backport TabCompleteEvent and AsyncTabCompleteEvent
  Patches applied cleanly to PandaSpigot-API
Resetting PandaSpigot-Server to PaperSpigot-Server...
HEAD is now at 3f6fdfe7f mc-dev Imports
  Applying patches to PandaSpigot-Server...
Applying: Fix Decompilation errors
...
Applying: Fix AIOOBE in inventory handling
~/panda-patch-rewrite (patch-system-rewrite) $
```

which is slower then current since the current one only applies our own patches if you rebuild and apply again for some reason

**Comment by hpfxd** [comment]
@mechoriet that no longer be the case as of e2e36c9ace81fd1ac76c58c1ed3344e162455a5c, is there anything else you'd like to see addressed?

**Comment by uRyanxD** [comment]
LGTM

**Comment by mechoriet** [comment]
LGTM

**Comment by uRyanxD** [comment]
@hpfxd This can be set directly instead of setting and replacing
https://github.com/hpfxd/PandaSpigot/blob/patch-system-rewrite/scripts/importmcdev.sh#L14

**Comment by uRyanxD** [comment]
LGTM

**Pull request merged**
